### ISSUE TITLE
主页bug测试

### ISSUE THREAD

**Issue by rRetr0Git** [rRetr0Git/rateMyCourse#13]
寻找主页的bug及可改进的地方，及时反馈到这个issue下
暂时先不考虑搜索部分

**Comment by liqingyang1606** [comment]
Selenium浏览器自动化测试框架
通过编写python代码，代替手工进行相应操作。
[相关教程](https://blog.csdn.net/TestingGDR/article/details/81950593)
里面包含了环境的搭建和元素查找、键盘输入、鼠标操作的相应函数。

自己由于没学过网页相关知识，学得比较慢，目前的代码只写了一点点：
```python
from selenium import webdriver
driver = webdriver.Ie()
driver.get("http://127.0.0.1:8000/")
```
运行上面的代码就可以直接在IE浏览器打开公课网。
目前自己遇到的难点主要是学习如何编写代码进行元素定位，鼠标和键盘操作的代码都还好写。

**Comment by rRetr0Git** [comment]
发现的不足和bug先汇总到这个issue下面
