### ISSUE TITLE
搜索页bug测试

### ISSUE THREAD

**Issue by rRetr0Git** [rRetr0Git/rateMyCourse#19]
利用测试框架，测试各种搜索姿势和成功性和正确性，汇总到这个issue下

**Comment by liqingyang1606** [comment]
在注册时出现的一个BUG：
<img width="960" alt="2019-04-15" src="https://user-images.githubusercontent.com/48213739/56138325-43149b80-5fc9-11e9-96ea-f22bab8df8e3.png">

如上图所示，报错信息为"mail repeated"
更换了多个邮箱仍存在同样的问题。

**Comment by rRetr0Git** [comment]
这个问题应该是因为你没有处理好数据库，我这里测试是没有问题的

**Comment by liqingyang1606** [comment]
位置：网站首页的“选择专业”下拉框
问题描述：先后两次runserver，点击该下拉框，发现专业的排序不一样。（同一次runserver时，多次访问网页不存在这一问题）
建议：按开课单位的教务编码，数值递增顺序进行排序。

**Comment by Niuyuhang03** [comment]
> 在注册时出现的一个BUG：
> <img alt="2019-04-15" width="960" src="https://user-images.githubusercontent.com/48213739/56138325-43149b80-5fc9-11e9-96ea-f22bab8df8e3.png">
> 
> 如上图所示，报错信息为"mail repeated"
> 更换了多个邮箱仍存在同样的问题。

可以清除一下数据库再导入一次数据，文档里有写具体操作。原因应该是你之前用这个邮箱注册过。也可以根据文档创建管理员后在https://127.0.0.1/admin直接看所有用户信息

**Comment by Niuyuhang03** [comment]
> 位置：网站首页的“选择专业”下拉框
> 问题描述：先后两次runserver，点击该下拉框，发现专业的排序不一样。（同一次runserver时，多次访问网页不存在这一问题）
> 建议：按开课单位的教务编码，数值递增顺序进行排序。

@rRetr0Git 为什么会出现这个问题？读取数据库没有order by应该会按行号读取吧？
