### ISSUE TITLE
测试

### ISSUE THREAD

**Issue by rRetr0Git** [rRetr0Git/rateMyCourse#28]
记录在这个issue下面

**Comment by waker-buaa** [comment]
导航栏问题，个人信息界面没有修改个人信息按钮，联系我们点击无效，没有搜索框

**Comment by liqingyang1606** [comment]
在IE浏览器下出现的一个Bug
在已登录状态下，访问某课程的信息页面，导航栏会变成未登录时的按钮。
如果在那里登录，将进入一个奇怪的页面：
<img width="960" alt="2019-04-20" src="https://user-images.githubusercontent.com/48213739/56452799-fb936400-6368-11e9-899b-253983168851.png">
如果进行评论，能够弹出评论成功提交的弹窗，但是没法查看（以前评的和刚交上去的都没法看到）

**Comment by liqingyang1606** [comment]
有两种情况没区分。一种是同一个课程由不同老师**分别**教授，一种是同一个课程由多个老师**协同**教授。“深度学习”课程显然属于后者，但是数据库却按照第一种情况处理了。
现在显示为三门课程：
<img width="960" alt="2019-04-21" src="https://user-images.githubusercontent.com/48213739/56465513-352fa200-6431-11e9-9aa5-392a276e3651.png">
实际应为一门课程。

**Comment by liqingyang1606** [comment]
mail repeated.的问题仍然存在，应该是邮箱字段设计过短造成的。
<img width="960" alt="2019-04-21 (1)" src="https://user-images.githubusercontent.com/48213739/56465558-11b92700-6432-11e9-9520-3e356865b1b9.png">
