### ISSUE TITLE
[BUG?]重复评价同一课程，先前评价不会被覆盖

### ISSUE THREAD

**Issue by fazdzz** [rRetr0Git/rateMyCourse#41]
RT，当前评价页面在进入后，即使我曾经评价过这门课，之前的评价也不会被加载出来。
同样的，编写的新的评价也不会替换原评价。
这样的话，一键刷爆差评的可行性是有的。

**Comment by rRetr0Git** [comment]
你好，之前的评论不会被加载这个问题能否提供截图？另外一个课程两次评价我们暂时确实没做要求，谢谢你的建议我们会再下一阶段改正

**Comment by fazdzz** [comment]
> 你好，之前的评论不会被加载这个问题能否提供截图？另外一个课程两次评价我们暂时确实没做要求，谢谢你的建议我们会再下一阶段改正

http://114.116.51.151/course/1408cc2f-f4d0-4ebf-82d1-4e47b123a5a4/
![image](https://user-images.githubusercontent.com/22709633/56506663-ca29bc80-6551-11e9-8515-be05dec40f98.png)

顺便发现一个新BUG，登录的时候跟我讲密码不能小于5个字符，但是注册的时候没要求，我只用了一个a就过了注册了，需要开一个新issue说这个事情吗

**Comment by liqingyang1606** [comment]
“之前的评价不会被加载”应该就是指同一门课程可以评价多次的问题。

**Comment by rRetr0Git** [comment]
注册和登录仍然不完善，感谢指出
