### ISSUE TITLE
[建议] 检索结果分页传送到前端

### ISSUE THREAD

**Issue by fazdzz** [rRetr0Git/rateMyCourse#42]
检索关键字为空时，1k+条数据会直接全部传送到前端，如下图，页面会在一开始有几秒钟没有做好分页，而显示全部结果。

![image](https://user-images.githubusercontent.com/22709633/56503932-87fc7d00-6549-11e9-988d-654931889f32.png)

当数据量很大时，这个页面的等待后端响应就会很久（可以通过chrome监视network流），之后下载数据也会很久，前端渲染也会很久。
具体有多久可以换一台网不那么好的设备直链访问来感受一下：http://114.116.51.151/search/?keywords=

可以考虑在后端对检索结果做分页，一次只传回几十条数据（区间SELECT），点击下一页的时候再向后端发请求索要后续数据。

**Comment by rRetr0Git** [comment]
好的我明白你的意思了，谢谢你的建议，为我们提供了改良思路，感谢
