### ISSUE TITLE
多机型测试工作

### ISSUE THREAD

**Issue by Melina-Zh** [rRetr0Git/rateMyCourse#47]
包括移动端和pc端多个浏览器的测试。持续到Beta阶段结束。

**Comment by Melina-Zh** [comment]
测试前请注意询问网站服务器端的release版本。

**Comment by Melina-Zh** [comment]
因为测试任务时间较长，建议每周一例会都有当前release版本的测试数据，作为工作量的展示，辛苦啦

**Comment by liqingyang1606** [comment]
“搜索结果”页面在分页上有一个BUG：偶尔出现空白页的情况。
样例：选择学校“北京航空航天大学”，选择学院“外国语学院”，搜索框输入文字“文学”
在返回的搜索结果页面中，第二页没有任何内容。
<img width="960" alt="2019-04-30" src="https://user-images.githubusercontent.com/48213739/56937314-912fb000-6b2e-11e9-800c-1cbd88cea941.png">

**Comment by liqingyang1606** [comment]
网站不能很好适配IE（包括有IE内核的）浏览器。
例如在Windows 10系统上，使用IE浏览器访问，用户的评论无法显示，
<img width="960" alt="2019-04-30 (2)" src="https://user-images.githubusercontent.com/48213739/56937464-68f48100-6b2f-11e9-95c6-c8c91b6b56be.png">

使用百度浏览器查看的用户评论偏离了矩形边框。
<img width="960" alt="2019-04-30 (1)" src="https://user-images.githubusercontent.com/48213739/56937445-47939500-6b2f-11e9-8e32-4b15d1906cd8.png">
