### ISSUE TITLE
网站安全性工作

### ISSUE THREAD

**Issue by Melina-Zh** [rRetr0Git/rateMyCourse#48]
增加登陆的邮箱验证和滑块验证。将密码转为密文。将cookie中用户名改为id等。

**Comment by Niuyuhang03** [comment]
cookie因为工作量有点大，邮箱验证和滑块验证还未完成，希望改为两个任务。

**Comment by Niuyuhang03** [comment]
滑动验证需要得到geetest账号，一周还没批下来。验证码需要的库已经不支持django2.0及以上。

**Comment by Melina-Zh** [comment]
好的
