### ISSUE TITLE
对测试出的bug进行修复

### ISSUE THREAD

**Issue by Melina-Zh** [rRetr0Git/rateMyCourse#58]
主要针对#issue45和#issue57中的问题进行修复，修复后将修复结果回复再issue中并且记录下来。
对例如#issue41，#issue42中的问题可以尝试复现bug，分析问题所在并记录下来。

**Comment by Niuyuhang03** [comment]
目前还有个bug是，只有主页的导航栏中，登录后点一个按钮，原本用户名的位置就会变成按钮名。在其他页面不存在

**Comment by Melina-Zh** [comment]
目前dev增加了在评论中点击用户名进入其个人主页的功能，且将cookie换成了session，现在只能保证尝试修改他人个人信息时实际上修改的是自己的个人信息，但不会报错，能否尝试在他人页面隐藏修改信息的按钮？

**Comment by waker-buaa** [comment]
> 目前dev增加了在评论中点击用户名进入其个人主页的功能，且将cookie换成了session，现在只能保证尝试修改他人个人信息时实际上修改的是自己的个人信息，但不会报错，能否尝试在他人页面隐藏修改信息的按钮？

Accepted

**Comment by waker-buaa** [comment]
> 目前还有个bug是，只有主页的导航栏中，登录后点一个按钮，原本用户名的位置就会变成按钮名。在其他页面不存在

Accepted

**Comment by Niuyuhang03** [comment]
注册后需要邮箱验证目前没有任何提示去邮箱中点击链接，麻烦增加一下相应的前端提示

**Comment by waker-buaa** [comment]
> 注册后需要邮箱验证目前没有任何提示去邮箱中点击链接，麻烦增加一下相应的前端提示

Accepted
